#ifndef RadioErrorsEnum_h__
#define RadioErrorsEnum_h__

typedef enum
{
	SKYRADIO_OK,
	SKYRADIO_ERROR,
	SKYRADIO_NOT_INITIALIZED,
	SKYRADIO_SEEK_ERROR,
	SKYRADIO_SIGNAL_ERROR,
	SKYRADIO_INSUFFICIENT_BUFFER,
	SKYRADIO_NULL_POINTER_PROVIDED
}SKYRADIO_RESULT;


#endif // RadioErrorsEnum_h__